Repository XRTK/Lumin, pull requests merged in 2020-05, with the labels that each got.

#75 Added preview package capabilities
  .gitignore
  XRTK.Lumin/Assets/XRTK.Generated.meta
  XRTK.Lumin/Assets/XRTK.Generated/Lumin.meta
  XRTK.Lumin/Assets/XRTK.Generated/SymbolicLinkSettings.asset
  XRTK.Lumin/Assets/XRTK.Generated/SymbolicLinkSettings.asset.meta
  XRTK.Lumin/Packages/com.xrtk.lumin/package.json
  XRTK.Lumin/Packages/manifest.json
  azure-pipelines.yml
  azure_pipelines/common.yml
  azure_pipelines/stages/publish.yml
  azure_pipelines/stages/steps/build-docs.yml
  azure_pipelines/stages/steps/build-unity-player.yml
  azure_pipelines/stages/steps/export-package-seed.yml
  azure_pipelines/stages/steps/install-unity.yml
  azure_pipelines/stages/steps/return-unity-license.yml
  azure_pipelines/stages/steps/run-unity-tests.yml
  azure_pipelines/stages/steps/upm-package-info.yml
  azure_pipelines/stages/unity-build.yml
Labels: Enhancement, Ready For Review

#76 updated github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/request_for_information.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Enhancement, Ready For Review

#78 fixed broken controller mapping
  XRTK.Lumin/Packages/com.xrtk.lumin/Profiles~/Controllers/LuminControllerDataProviderProfile.asset
Labels: Bug, Ready For Review

#79 Update default near clip plane
  XRTK.Lumin/Packages/com.xrtk.lumin/Profiles~/CameraSystem/LuminCameraDataProvider.asset
Labels: Ready For Review
